services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "./data/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  front:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}nginx:${GCF_ED}{MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "$MAILU_WEB_PORT:80"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    networks:
      - default
      - webmail
    volumes:
      - "./data/certs:/certs"
      - "./data/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}unbound:${GCF_ED}{MAILU_VERSION:-2024.06}
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}admin:${GCF_ED}{MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "./data/data:/data"
      - "./data/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}dovecot:${GCF_ED}{MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "./data/mail:/mail"
      - "./data/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}postfix:${GCF_ED}{MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "./data/mailqueue:/queue"
      - "./data/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}oletools:${GCF_ED}{MAILU_VERSION:-2.0}
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}rspamd:${GCF_ED}{MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
      - clamav
    volumes:
      - "./data/filter:/var/lib/rspamd"
      - "./data/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  antivirus:
    image: clamav/clamav-debian:1.2.0-6
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-antivirus
    networks:
      - clamav
    volumes:
      - "./data/filter/clamav:/var/lib/clamav"
    healthcheck:
      test: ["CMD-SHELL", "kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webmail:
    image: ${GCF_ED}{DOCKER_ORG:-ghcr.io/mailu}/${GCF_ED}{DOCKER_PREFIX:-}webmail:${GCF_ED}{MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "./data/webmail:/data"
      - "./data/overrides/snappymail:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  clamav:
    driver: bridge
  oletools:
    driver: bridge
    internal: true
