services:
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - "/mailu/redis:/data"
        networks:
            - default
            - webmail
        dns:
            - 192.168.203.254

    front:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
        restart: always
        env_file: ./mailu.env
        logging:
            driver: journald
            options:
                tag: mailu-front
        ports:
            - "8080:80"
            - "25:25"
            - "465:465"
            - "587:587"
            - "110:110"
            - "995:995"
            - "143:143"
            - "993:993"
        networks:
            - default
            - webmail
        volumes:
            - "/mailu/certs:/certs"
            - "/mailu/overrides/nginx:/overrides:ro"
        depends_on:
            - resolver
        dns:
            - 192.168.203.254

    resolver:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
        env_file: ./mailu.env
        restart: always
        networks:
            default:
                ipv4_address: 192.168.203.254
        dns:
            - 192.168.203.254

    admin:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
        restart: always
        env_file: ./mailu.env
        logging:
            driver: journald
            options:
                tag: mailu-admin
        volumes:
            - "/mailu/data:/data"
            - "/mailu/dkim:/dkim"
        depends_on:
            - redis
            - resolver
        dns:
            - 192.168.203.254

    imap:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
        restart: always
        env_file: ./mailu.env
        logging:
            driver: journald
            options:
                tag: mailu-imap
        volumes:
            - "/mailu/mail:/mail"
            - "/mailu/overrides/dovecot:/overrides:ro"
        depends_on:
            - front
            - resolver
        dns:
            - 192.168.203.254

    smtp:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
        restart: always
        env_file: ./mailu.env
        logging:
            driver: journald
            options:
                tag: mailu-smtp
        volumes:
            - "/mailu/mailqueue:/queue"
            - "/mailu/overrides/postfix:/overrides:ro"
        depends_on:
            - front
            - resolver
        dns:
            - 192.168.203.254

    oletools:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
        hostname: oletools
        restart: always
        networks:
            - noinet
        dns:
            - 192.168.203.254

    antispam:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
        hostname: antispam
        restart: always
        env_file: ./mailu.env
        logging:
            driver: journald
            options:
                tag: mailu-antispam
        networks:
            - default
            - noinet
        volumes:
            - "/mailu/filter:/var/lib/rspamd"
            - "/mailu/overrides/rspamd:/overrides:ro"
        depends_on:
            - front
            - redis
            - oletools
            - antivirus
            - resolver
        dns:
            - 192.168.203.254

    antivirus:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
        restart: always
        env_file: ./mailu.env
        volumes:
            - "/mailu/filter:/data"
        depends_on:
            - resolver
        dns:
            - 192.168.203.254

    fetchmail:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
        restart: always
        env_file: ./mailu.env
        volumes:
            - "/mailu/data/fetchmail:/data"
        depends_on:
            - admin
            - smtp
            - imap
            - resolver
        dns:
            - 192.168.203.254

    webmail:
        image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
        restart: always
        env_file: ./mailu.env
        volumes:
            - "/mailu/webmail:/data"
            - "/mailu/overrides/snappymail:/overrides:ro"
        networks:
            - webmail
        depends_on:
            - front

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.203.0/24
    webmail:
        driver: bridge
    noinet:
        driver: bridge
        internal: true
